//! Generated built-in metadata. The table is intentionally deterministic and reviewed in tests.

use sugra_domain::{
    Capability, DomainError, LegacyId, OptionDefinition, OptionKind, ScannerDescriptor, ScannerId,
    TargetKind,
};

use crate::definition::{Operation, ScannerDefinition};

#[allow(clippy::too_many_lines)]
pub(crate) fn definitions() -> Result<Vec<ScannerDefinition>, DomainError> {
    Ok(vec![
        definition(
            LegacyId::Catalog(20),
            "asn-lookup",
            "ASN Lookup",
            Operation::Registry,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::PassiveNetwork],
            &["ips_file", "provider", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(1),
            "associated-hosts",
            "Associated Hosts",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::ThirdPartyApi],
            &["sources", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(39),
            "autonomous-neighbor-peering-map",
            "Autonomous Neighbor Peering Map",
            Operation::Registry,
            vec![TargetKind::Asn, TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(26),
            "bgp-route-analysis",
            "BGP Route Analysis",
            Operation::Registry,
            vec![TargetKind::Asn, TargetKind::Cidr],
            vec![Capability::PassiveNetwork],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(27),
            "cdn-detection",
            "CDN Detection",
            Operation::Http,
            vec![TargetKind::Domain],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(2),
            "dns-over-https",
            "DNS Over HTTPS",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["providers", "qtype", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(3),
            "dns-records",
            "DNS Records",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["timeout", "types"],
        )?,
        definition(
            LegacyId::Catalog(33),
            "dns-sla-latency-monitor",
            "DNS SLA Latency Monitor",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["resolvers", "samples", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(4),
            "dnssec",
            "DNSSEC Check",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["check_subdomains", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(5),
            "domain-info",
            "Domain Info",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(6),
            "domain-reputation-check",
            "Domain Reputation Check",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &["timeout", "vt_key"],
        )?,
        definition(
            LegacyId::Catalog(36),
            "dual-stack-behavior-profiler",
            "Dual‑Stack Behavior Profiler",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["limit", "paths", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(30),
            "geo-dns-footprint",
            "Geo‑DNS Footprint",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(7),
            "http2-http3-checker",
            "HTTP/2 and HTTP/3 Support Checker",
            Operation::Tls,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(37),
            "icmp-reachability-matrix",
            "ICMP Reachability Matrix",
            Operation::Command,
            vec![TargetKind::Domain, TargetKind::Ip, TargetKind::Cidr],
            vec![Capability::LocalExec],
            &["max_hosts", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(38),
            "ip-allocation-history-tracker",
            "IP Allocation History Tracker",
            Operation::Intelligence,
            vec![TargetKind::Ip, TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(8),
            "ip-info",
            "IP Info",
            Operation::Registry,
            vec![TargetKind::Ip, TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Catalog(22),
            "ip-range-scanner",
            "IP Range Scanner",
            Operation::Tcp,
            vec![TargetKind::Cidr, TargetKind::Ip],
            vec![Capability::ActiveProtocol],
            &["max_hosts", "ports", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(25),
            "ipv6-reachability-test",
            "IPv6 Reachability Test",
            Operation::Tcp,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::ActiveProtocol],
            &["max_hosts", "threads", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(41),
            "network-certificate-inventory",
            "Network Certificate Inventory",
            Operation::Tcp,
            vec![TargetKind::Domain, TargetKind::Ip, TargetKind::Cidr],
            vec![Capability::ActiveProtocol],
            &["max_hosts", "ports", "server_name", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(29),
            "network-timezone-detection",
            "Network Timezone Detection",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(32),
            "ns-geo-asn-diversity-analyzer",
            "NS Geo/ASN Diversity Analyzer",
            Operation::Registry,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Catalog(24),
            "ntp-info-leak-checker",
            "NTP Information Leak Checker",
            Operation::Udp,
            vec![TargetKind::Ip, TargetKind::Domain],
            vec![Capability::ActiveProtocol],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(9),
            "open-ports",
            "Open Ports Scan",
            Operation::Tcp,
            vec![TargetKind::Ip, TargetKind::Domain],
            vec![Capability::ActiveProtocol],
            &["ports", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(23),
            "rdap-lookup",
            "RDAP Lookup",
            Operation::Registry,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::PassiveNetwork],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(35),
            "recursive-nameserver-leak-test",
            "Recursive Nameserver Leak Test",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(28),
            "reverse-dns-scan",
            "Reverse DNS Scan",
            Operation::Dns,
            vec![TargetKind::Ip, TargetKind::Cidr],
            vec![Capability::PassiveNetwork],
            &["workers"],
        )?,
        definition(
            LegacyId::Catalog(21),
            "reverse-ip-lookup",
            "Reverse IP Lookup",
            Operation::Intelligence,
            vec![TargetKind::Ip],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(34),
            "rpki-route-validity-check",
            "RPKI Route Validity Check",
            Operation::Registry,
            vec![TargetKind::Cidr, TargetKind::Asn],
            vec![Capability::PassiveNetwork],
            &["asn", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(10),
            "server-info",
            "Server Info",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(11),
            "server-location",
            "Server Location",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(43),
            "snmp-public-community-checker",
            "SNMP Public Community Checker",
            Operation::Udp,
            vec![TargetKind::Domain, TargetKind::Ip, TargetKind::Cidr],
            vec![Capability::ActiveProtocol],
            &["max_hosts", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(31),
            "spf-network-extractor",
            "SPF Network Extractor",
            Operation::Dns,
            vec![TargetKind::Domain, TargetKind::Email],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Catalog(42),
            "ssh-banner-key-fingerprinter",
            "SSH Banner & Key Fingerprinter",
            Operation::Command,
            vec![TargetKind::Domain, TargetKind::Ip, TargetKind::Cidr],
            vec![Capability::LocalExec],
            &["max_hosts", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(12),
            "ssl-chain",
            "SSL Chain Analysis",
            Operation::Tls,
            vec![TargetKind::Domain, TargetKind::HostPort],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(13),
            "ssl-expiry",
            "SSL Expiry Alert",
            Operation::Tls,
            vec![TargetKind::Domain, TargetKind::HostPort],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(14),
            "tls-cipher-suites",
            "TLS Cipher Suites",
            Operation::Tls,
            vec![TargetKind::Domain, TargetKind::HostPort],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(15),
            "tls-handshake",
            "TLS Handshake Simulation",
            Operation::Tls,
            vec![TargetKind::Domain, TargetKind::HostPort],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(40),
            "tls-session-resumption-map",
            "TLS Session Resumption Map",
            Operation::Tcp,
            vec![TargetKind::Domain, TargetKind::Ip, TargetKind::Cidr],
            vec![Capability::ActiveProtocol],
            &["max_hosts", "ports", "samples", "server_name", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(16),
            "traceroute",
            "Traceroute",
            Operation::Command,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::LocalExec],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(17),
            "txt-records",
            "TXT Records",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Catalog(44),
            "udp-service-sampler",
            "UDP Service Sampler",
            Operation::Udp,
            vec![TargetKind::Domain, TargetKind::Ip, TargetKind::Cidr],
            vec![Capability::ActiveProtocol],
            &["max_hosts", "ports", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(18),
            "whois-lookup",
            "WHOIS Lookup",
            Operation::Command,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::LocalExec],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(19),
            "zonetransfer",
            "Zone Transfer",
            Operation::Tcp,
            vec![TargetKind::Domain],
            vec![Capability::ActiveProtocol],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(82),
            "api-schema-grabber",
            "API Schema Grabber",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["delay", "graphql_paths", "paths", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(45),
            "archive-history",
            "Archive History",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ThirdPartyApi],
            &["collapse_digest", "limit", "status_filter", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(75),
            "autocomplete-vulnerability-checker",
            "Autocomplete Vulnerability Checker",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["max_pages", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(46),
            "broken-links",
            "Broken Links Detection",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["max_pages", "sample_ratio", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(88),
            "cache-behavior-analyzer",
            "Cache Behavior Analyzer",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["max_pages", "sample_ratio", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(70),
            "captcha-presence-checker",
            "CAPTCHA Presence Checker",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["max_pages", "sample_ratio", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(47),
            "carbon-footprint",
            "Carbon Footprint",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(66),
            "clickjacking-test",
            "Clickjacking Test",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["max_pages", "sample_ratio", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(48),
            "cms-detection",
            "CMS Detection",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(50),
            "content-discovery",
            "Content Discovery",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &["include_subdomains", "max_pages"],
        )?,
        definition(
            LegacyId::Catalog(89),
            "cookie-scope-diff",
            "Cookie Scope Diff Across Subdomains",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["include_subdomains", "max_pages"],
        )?,
        definition(
            LegacyId::Catalog(49),
            "cookies",
            "Cookies Analyzer",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["follow", "paths", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(63),
            "cors-misconfiguration-scanner",
            "CORS Misconfiguration Scanner",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(52),
            "crawl-rules",
            "Robots.txt Analyzer",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(51),
            "crawler",
            "Crawler",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &["depth", "max_pages", "rate_limit", "start_url"],
        )?,
        definition(
            LegacyId::Catalog(90),
            "csp-deep-analyzer",
            "CSP Deep Analyzer",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["max_pages", "sample_ratio", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(80),
            "dependency-js-cdn-scanner",
            "Dependency JS/CDN Scanner",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["max_pages", "sample_ratio", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(53),
            "directory-finder",
            "Directory Finder",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &["status_keep", "timeout", "wordlist"],
        )?,
        definition(
            LegacyId::Catalog(87),
            "dom-sink-scanner",
            "DOM Sink Scanner",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["max_pages", "sample_ratio", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(54),
            "email-harvester",
            "Email Harvesting",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz, Capability::SensitiveOutput],
            &[],
        )?,
        definition(
            LegacyId::Catalog(76),
            "embedded-object-hunter",
            "Embedded Object Hunter",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(68),
            "favicon-hashing",
            "Favicon Hashing",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(86),
            "file-upload-surface-finder",
            "File Upload Surface Finder",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &["include_subs", "max_pages", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(67),
            "form-grabber",
            "Form Grabber",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["include_subs", "max_pages", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(85),
            "graphql-introspection-probe",
            "GraphQL Introspection Probe",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &[],
        )?,
        definition(
            LegacyId::Catalog(65),
            "hidden-parameter-discovery",
            "Hidden Parameter Discovery",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &[
                "max_params",
                "params_file",
                "test_values",
                "threshold",
                "timeout",
            ],
        )?,
        definition(
            LegacyId::Catalog(74),
            "html5-feature-abuse-detector",
            "HTML5 Feature Abuse Detector",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(69),
            "html-comments-extractor",
            "HTML Comments Extractor",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(84),
            "http-method-enumerator",
            "HTTP Method Enumerator",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(62),
            "javascript-file-analyzer",
            "JavaScript File Analyzer",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(71),
            "javascript-obfuscation-detector",
            "JavaScript Obfuscation Detector",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[
                "export_txt",
                "include_subdomains",
                "max_pages",
                "max_scripts",
                "timeout",
            ],
        )?,
        definition(
            LegacyId::Catalog(83),
            "lazy-load-resource-finder",
            "Lazy-Load Resource Finder",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(64),
            "login-page-brute-identifier",
            "Login Page Brute Identifier",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &["follow_redirects", "paths", "paths_file", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(77),
            "multi-language-url-tester",
            "Multi-Language URL Tester",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(55),
            "performance-monitoring",
            "Performance Monitoring",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["key", "strategies", "timeout", "verify_ssl"],
        )?,
        definition(
            LegacyId::Catalog(78),
            "pixel-tracker-finder",
            "Pixel Tracker Finder",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(56),
            "quality-metrics",
            "Quality Metrics",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(57),
            "redirect-chain",
            "Redirect Chain",
            Operation::Http,
            vec![TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(79),
            "seo-abuse-detector",
            "SEO Abuse Detector",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(73),
            "session-cookie-lifetime-checker",
            "Session Cookie Lifetime Checker",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(58),
            "sitemap",
            "Sitemap Parsing",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(59),
            "social-media",
            "Social Media Presence Scan",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(92),
            "static-asset-fingerprinter",
            "Static Asset Fingerprinter",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(60),
            "technology-stack",
            "Technology Stack Detection",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(61),
            "third-party-integrations",
            "Third-Party Integrations",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(91),
            "third-party-script-risk-profiler",
            "Third-Party Script Risk Profiler",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(72),
            "virtual-host-fuzzer",
            "Virtual Host Fuzzer",
            Operation::Http,
            vec![TargetKind::Domain],
            vec![Capability::ActiveFuzz],
            &[],
        )?,
        definition(
            LegacyId::Catalog(81),
            "websocket-endpoint-sniffer",
            "WebSocket Endpoint Sniffer",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(130),
            "attack-surface-delta",
            "Attack Surface Delta",
            Operation::Http,
            vec![TargetKind::Domain],
            vec![Capability::ActiveHttpSafe],
            &["ports_top", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(112),
            "breached-credentials-lookup",
            "Breached Credentials Lookup",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Email],
            vec![Capability::ThirdPartyApi, Capability::SensitiveOutput],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(127),
            "bug-bounty-program-finder",
            "Bug Bounty Program Finder",
            Operation::Http,
            vec![TargetKind::Domain],
            vec![Capability::ActiveHttpSafe],
            &["timeout", "workers"],
        )?,
        definition(
            LegacyId::Catalog(93),
            "censys",
            "Censys Reconnaissance",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::ThirdPartyApi],
            &["concurrency"],
        )?,
        definition(
            LegacyId::Catalog(94),
            "certificate-authority-recon",
            "Certificate Authority Recon",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(113),
            "cloud-bucket-exposure",
            "Cloud Bucket Exposure",
            Operation::Http,
            vec![TargetKind::Domain],
            vec![Capability::ActiveFuzz],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(125),
            "cloud-service-enumeration",
            "Cloud Service Enumeration",
            Operation::Http,
            vec![TargetKind::Domain],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(111),
            "ct-log-query",
            "CT Log Query",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &["include_wildcard", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(128),
            "custom-wordlist-generator",
            "Custom Wordlist Generator",
            Operation::Local,
            vec![TargetKind::Domain],
            vec![Capability::LocalAnalysis],
            &[],
        )?,
        definition(
            LegacyId::Catalog(95),
            "data-leak",
            "Data Leak Detection",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi, Capability::SensitiveOutput],
            &[],
        )?,
        definition(
            LegacyId::Catalog(133),
            "domain-shadowing-detector",
            "Domain Shadowing Detector",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &["days", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(115),
            "exposed-api-endpoints",
            "Exposed API Endpoints",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &[],
        )?,
        definition(
            LegacyId::Catalog(96),
            "exposed-env-files",
            "Exposed Environment Files Checker",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &[],
        )?,
        definition(
            LegacyId::Catalog(97),
            "firewall-detection",
            "Firewall Detection",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::ActiveHttpSafe],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(116),
            "git-repo-exposure-check",
            "Git Repository Exposure Check",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(98),
            "global-ranking",
            "Global Ranking",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(99),
            "http-headers",
            "HTTP Headers",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(100),
            "http-security",
            "HTTP Security Features",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &["json", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(134),
            "ip-reputation-trending",
            "IP Reputation Trending",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Ip, TargetKind::Cidr],
            vec![Capability::ThirdPartyApi],
            &["long_window", "short_window"],
        )?,
        definition(
            LegacyId::Catalog(124),
            "js-malware-scanner",
            "JS Malware Scanner",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ThirdPartyApi],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(114),
            "jwt-token-analyzer",
            "JWT Token Analyzer",
            Operation::Local,
            vec![TargetKind::Opaque],
            vec![Capability::LocalAnalysis, Capability::SensitiveOutput],
            &[],
        )?,
        definition(
            LegacyId::Catalog(101),
            "malware-phishing",
            "Malware & Phishing Check",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(119),
            "open-redirect-finder",
            "Open Redirect Finder",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &["timeout"],
        )?,
        definition(
            LegacyId::Catalog(131),
            "passive-cve-mapper",
            "Passive CVE Mapper",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(102),
            "pastebin-monitoring",
            "Pastebin Monitoring",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi, Capability::SensitiveOutput],
            &[],
        )?,
        definition(
            LegacyId::Catalog(103),
            "privacy-gdpr",
            "Privacy & GDPR Compliance",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(120),
            "rate-limit-waf-bypass-test",
            "Rate-Limit & WAF Bypass Test",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveFuzz],
            &["batch_size", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(123),
            "rogue-certificate-check",
            "Rogue Certificate Check",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(126),
            "rogue-subdomain-resolver",
            "Rogue Subdomain Resolver",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Catalog(121),
            "security-changelog-diff",
            "Security Changelog Diff",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(132),
            "security-contact-gap-finder",
            "Security Contact Gap Finder",
            Operation::Http,
            vec![TargetKind::Domain],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(104),
            "security-txt",
            "Security.txt Check",
            Operation::Http,
            vec![TargetKind::Domain],
            vec![Capability::ActiveHttpSafe],
            &["log", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(122),
            "session-hijacking-passive",
            "Session Hijacking (Passive)",
            Operation::Http,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe, Capability::SensitiveOutput],
            &["paths", "session_hints", "timeout"],
        )?,
        definition(
            LegacyId::Catalog(105),
            "shodan",
            "Shodan Reconnaissance",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(118),
            "spf-dkim-dmarc-validator",
            "SPF / DKIM / DMARC Validator",
            Operation::Dns,
            vec![TargetKind::Domain, TargetKind::Email],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Catalog(106),
            "ssl-labs-report",
            "SSL Labs Report",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(107),
            "ssl-pinning-check",
            "SSL Pinning Check",
            Operation::Tls,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Catalog(108),
            "subdomain-enum",
            "Subdomain Enumeration",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(109),
            "subdomain-takeover",
            "Subdomain Takeover",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Catalog(129),
            "threat-feed-correlator",
            "Threat Feed Correlator",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Catalog(117),
            "typosquat-domain-checker",
            "Typosquat Domain Checker",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork, Capability::LocalAnalysis],
            &["max_variants"],
        )?,
        definition(
            LegacyId::Catalog(110),
            "virustotal-scan",
            "VirusTotal Scan",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Ip, TargetKind::Url],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Additional(1),
            "dark-web-monitoring",
            "dark_web_monitoring",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ThirdPartyApi, Capability::SensitiveOutput],
            &[],
        )?,
        definition(
            LegacyId::Additional(2),
            "decoy-dns-beacon",
            "decoy_dns_beacon",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Additional(3),
            "dns-caa-checker",
            "dns_caa_checker",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Additional(4),
            "dual-stack-diff",
            "dual_stack_diff",
            Operation::Dns,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Additional(5),
            "email-config",
            "email_config",
            Operation::Dns,
            vec![TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Additional(6),
            "geo-ip-spoof-detection",
            "geo_ip_spoof_detection",
            Operation::Intelligence,
            vec![TargetKind::Ip, TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Additional(7),
            "ip-reputation-check",
            "ip_reputation_check",
            Operation::Intelligence,
            vec![TargetKind::Domain, TargetKind::Url],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Additional(8),
            "irr-routing-registry-analyzer",
            "irr_routing_registry_analyzer",
            Operation::Registry,
            vec![TargetKind::Asn, TargetKind::Ip, TargetKind::Domain],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
        definition(
            LegacyId::Additional(9),
            "netbios-name-query",
            "netbios_name_query",
            Operation::Udp,
            vec![TargetKind::Ip, TargetKind::Domain],
            vec![Capability::ActiveProtocol],
            &["timeout"],
        )?,
        definition(
            LegacyId::Additional(10),
            "passive-dns-history",
            "passive_dns_history",
            Operation::Intelligence,
            vec![TargetKind::Domain],
            vec![Capability::ThirdPartyApi],
            &[],
        )?,
        definition(
            LegacyId::Additional(11),
            "snmp-bulk-walk",
            "snmp_bulk_walk",
            Operation::Udp,
            vec![TargetKind::Ip, TargetKind::Domain],
            vec![Capability::ActiveProtocol],
            &["timeout"],
        )?,
        definition(
            LegacyId::Additional(12),
            "tls-security-config",
            "tls_security_config",
            Operation::Tls,
            vec![TargetKind::Domain],
            vec![Capability::ActiveHttpSafe],
            &[],
        )?,
        definition(
            LegacyId::Additional(13),
            "ttl-analysis",
            "ttl_analysis",
            Operation::Dns,
            vec![TargetKind::Domain, TargetKind::Ip],
            vec![Capability::PassiveNetwork],
            &[],
        )?,
    ])
}

fn definition(
    legacy_id: LegacyId,
    id: &str,
    name: &str,
    operation: Operation,
    target_kinds: Vec<TargetKind>,
    capabilities: Vec<Capability>,
    option_names: &[&str],
) -> Result<ScannerDefinition, DomainError> {
    Ok(ScannerDefinition {
        descriptor: ScannerDescriptor {
            id: ScannerId::new(id)?,
            legacy_id: Some(legacy_id),
            name: name.into(),
            description: format!("Collects and evaluates {name} evidence."),
            track: track(operation).into(),
            target_kinds,
            capabilities,
            options: option_names.iter().map(|name| option(name)).collect(),
            version: "1".into(),
        },
        operation,
    })
}

fn track(operation: Operation) -> &'static str {
    match operation {
        Operation::Dns => "dns",
        Operation::Http => "web-observation",
        Operation::Tls => "tls",
        Operation::Registry => "registry",
        Operation::Intelligence => "intelligence",
        Operation::Tcp | Operation::Udp => "active-network",
        Operation::Command => "platform-network",
        Operation::Local => "local-analysis",
    }
}

fn option(name: &str) -> OptionDefinition {
    let lower = name.to_ascii_lowercase();
    let kind = if lower.contains("key") || lower.contains("secret") || lower.contains("token") {
        OptionKind::SecretRef
    } else if lower.starts_with("include")
        || lower.starts_with("check")
        || lower.starts_with("follow")
        || lower.starts_with("collapse")
        || lower == "log"
    {
        OptionKind::Boolean
    } else if [
        "timeout",
        "workers",
        "threads",
        "concurrency",
        "samples",
        "limit",
        "max_pages",
        "max_hosts",
        "max_variants",
        "depth",
        "delay",
        "rate_limit",
        "sample_ratio",
        "ports_top",
        "short_window",
        "long_window",
        "days",
    ]
    .iter()
    .any(|candidate| lower.contains(candidate))
    {
        OptionKind::Integer {
            min: 1,
            max: 100_000,
        }
    } else if [
        "ports",
        "types",
        "paths",
        "sources",
        "providers",
        "resolvers",
        "status",
        "wordlist",
        "graphql",
    ]
    .iter()
    .any(|candidate| lower.contains(candidate))
    {
        OptionKind::List { max_items: 1_024 }
    } else {
        OptionKind::Text { max_len: 4_096 }
    };
    OptionDefinition {
        key: name.into(),
        description: format!("Configuration value for {name}."),
        default: secret_default(name),
        required: false,
        kind,
    }
}

fn secret_default(name: &str) -> Option<String> {
    match name.to_ascii_lowercase().as_str() {
        "vt_key" | "virustotal_key" => Some("VIRUSTOTAL_API_KEY".into()),
        "shodan_key" => Some("SHODAN_API_KEY".into()),
        "censys_key" => Some("CENSYS_API_SECRET".into()),
        _ => None,
    }
}
